// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MeliSample {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm searchForm;
		
		protected System.Web.UI.WebControls.DropDownList DDLsites;
		
		protected System.Web.UI.WebControls.DropDownList DDLcategories;
		
		protected System.Web.UI.WebControls.TextBox textInput;
		
		protected System.Web.UI.WebControls.Button btnSearch;
		
		protected System.Web.UI.WebControls.PlaceHolder resultsPlaceHolder;
	}
}
